FROM selenium/standalone-chrome
USER root
WORKDIR /app
RUN wget https://bootstrap.pypa.io/get-pip.py \
    && python3 get-pip.py \
    && python3 -m pip install selenium
ADD . /app

CMD ["python3" , "src/main.py"]